var annotated_dup =
[
    [ "Core", "namespaceCore.html", [
      [ "Context", "classCore_1_1Context.html", "classCore_1_1Context" ],
      [ "Drawable", "classCore_1_1Drawable.html", null ],
      [ "IndexBuffer", "classCore_1_1IndexBuffer.html", null ],
      [ "Matrices", "structCore_1_1Matrices.html", null ],
      [ "Program", "classCore_1_1Program.html", null ],
      [ "Shader", "classCore_1_1Shader.html", null ],
      [ "Texture", "classCore_1_1Texture.html", null ],
      [ "UniformBuffer", "classCore_1_1UniformBuffer.html", null ],
      [ "VertexArray", "classCore_1_1VertexArray.html", "classCore_1_1VertexArray" ],
      [ "VertexBuffer", "classCore_1_1VertexBuffer.html", null ]
    ] ],
    [ "fmt", null, [
      [ "formatter< Util::Transform >", "structfmt_1_1formatter_3_01Util_1_1Transform_01_4.html", null ]
    ] ],
    [ "Game", null, [
      [ "Enemy", null, [
        [ "Enemy", "classGame_1_1Enemy_1_1Enemy.html", null ]
      ] ],
      [ "Passive", null, [
        [ "Passive", "classGame_1_1Passive_1_1Passive.html", null ]
      ] ],
      [ "Projectile", null, [
        [ "Projectile", "classGame_1_1Projectile_1_1Projectile.html", null ],
        [ "Stats", "structGame_1_1Projectile_1_1Stats.html", null ],
        [ "Vampirica", "classGame_1_1Projectile_1_1Vampirica.html", null ],
        [ "Whip", "classGame_1_1Projectile_1_1Whip.html", null ]
      ] ],
      [ "Util", null, [
        [ "Animated", "classGame_1_1Util_1_1Animated.html", null ],
        [ "Animation", "classGame_1_1Util_1_1Animation.html", null ],
        [ "Mirrored", "classGame_1_1Util_1_1Mirrored.html", null ],
        [ "ObjectPool", "classGame_1_1Util_1_1ObjectPool.html", null ],
        [ "Offsetted", "classGame_1_1Util_1_1Offsetted.html", null ],
        [ "Physical", "classGame_1_1Util_1_1Physical.html", null ],
        [ "QuadTree", "classGame_1_1Util_1_1QuadTree.html", null ],
        [ "Size", "structGame_1_1Util_1_1Size.html", null ],
        [ "Timer", "classGame_1_1Util_1_1Timer.html", null ]
      ] ],
      [ "Weapon", null, [
        [ "Vampirica", "classGame_1_1Weapon_1_1Vampirica.html", null ],
        [ "Weapon", "classGame_1_1Weapon_1_1Weapon.html", null ],
        [ "Whip", "classGame_1_1Weapon_1_1Whip.html", null ]
      ] ],
      [ "Camera", "classGame_1_1Camera.html", null ],
      [ "Character", "classGame_1_1Character.html", null ],
      [ "Manager", "classGame_1_1Manager.html", null ],
      [ "Map", "classGame_1_1Map.html", null ],
      [ "Resource", "classGame_1_1Resource.html", null ]
    ] ],
    [ "nlohmann", "namespacenlohmann.html", [
      [ "detail", "namespacenlohmann_1_1detail.html", [
        [ "dtoa_impl", "namespacenlohmann_1_1detail_1_1dtoa__impl.html", [
          [ "boundaries", "structnlohmann_1_1detail_1_1dtoa__impl_1_1boundaries.html", null ],
          [ "cached_power", "structnlohmann_1_1detail_1_1dtoa__impl_1_1cached__power.html", null ],
          [ "diyfp", "structnlohmann_1_1detail_1_1dtoa__impl_1_1diyfp.html", null ]
        ] ],
        [ "binary_reader", "classnlohmann_1_1detail_1_1binary__reader.html", "classnlohmann_1_1detail_1_1binary__reader" ],
        [ "binary_writer", "classnlohmann_1_1detail_1_1binary__writer.html", "classnlohmann_1_1detail_1_1binary__writer" ],
        [ "conjunction", "structnlohmann_1_1detail_1_1conjunction.html", null ],
        [ "conjunction< B1 >", "structnlohmann_1_1detail_1_1conjunction_3_01B1_01_4.html", null ],
        [ "conjunction< B1, Bn... >", "structnlohmann_1_1detail_1_1conjunction_3_01B1_00_01Bn_8_8_8_01_4.html", null ],
        [ "detector", "structnlohmann_1_1detail_1_1detector.html", null ],
        [ "detector< Default, void_t< Op< Args... > >, Op, Args... >", "structnlohmann_1_1detail_1_1detector_3_01Default_00_01void__t_3_01Op_3_01Args_8_8_8_01_4_01_4_00_01Op_00_01Args_8_8_8_01_4.html", null ],
        [ "exception", "classnlohmann_1_1detail_1_1exception.html", "classnlohmann_1_1detail_1_1exception" ],
        [ "external_constructor", "structnlohmann_1_1detail_1_1external__constructor.html", null ],
        [ "external_constructor< value_t::array >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1array_01_4.html", null ],
        [ "external_constructor< value_t::boolean >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1boolean_01_4.html", null ],
        [ "external_constructor< value_t::number_float >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__float_01_4.html", null ],
        [ "external_constructor< value_t::number_integer >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__integer_01_4.html", null ],
        [ "external_constructor< value_t::number_unsigned >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4.html", null ],
        [ "external_constructor< value_t::object >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1object_01_4.html", null ],
        [ "external_constructor< value_t::string >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1string_01_4.html", null ],
        [ "file_input_adapter", "classnlohmann_1_1detail_1_1file__input__adapter.html", "classnlohmann_1_1detail_1_1file__input__adapter" ],
        [ "from_json_fn", "structnlohmann_1_1detail_1_1from__json__fn.html", null ],
        [ "has_from_json", "structnlohmann_1_1detail_1_1has__from__json.html", null ],
        [ "has_from_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__from__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01not_5e786a91cad76ed1c14f425887b41640.html", null ],
        [ "has_non_default_from_json", "structnlohmann_1_1detail_1_1has__non__default__from__json.html", null ],
        [ "has_non_default_from_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__non__default__from__json_3_01BasicJsonType_00_01T_00_01enable__a9e4562f31f7ed523e6e0f675606b0f2.html", null ],
        [ "has_to_json", "structnlohmann_1_1detail_1_1has__to__json.html", null ],
        [ "has_to_json< BasicJsonType, T, enable_if_t< not is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__to__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01not_01737900a749c335e922e2f74e2face5e4.html", null ],
        [ "index_sequence", "structnlohmann_1_1detail_1_1index__sequence.html", null ],
        [ "input_adapter", "classnlohmann_1_1detail_1_1input__adapter.html", "classnlohmann_1_1detail_1_1input__adapter" ],
        [ "input_adapter_protocol", "structnlohmann_1_1detail_1_1input__adapter__protocol.html", "structnlohmann_1_1detail_1_1input__adapter__protocol" ],
        [ "input_buffer_adapter", "classnlohmann_1_1detail_1_1input__buffer__adapter.html", "classnlohmann_1_1detail_1_1input__buffer__adapter" ],
        [ "input_stream_adapter", "classnlohmann_1_1detail_1_1input__stream__adapter.html", "classnlohmann_1_1detail_1_1input__stream__adapter" ],
        [ "internal_iterator", "structnlohmann_1_1detail_1_1internal__iterator.html", "structnlohmann_1_1detail_1_1internal__iterator" ],
        [ "invalid_iterator", "classnlohmann_1_1detail_1_1invalid__iterator.html", null ],
        [ "is_basic_json", "structnlohmann_1_1detail_1_1is__basic__json.html", null ],
        [ "is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "structnlohmann_1_1detail_1_1is__basic__json_3_01NLOHMANN__BASIC__JSON__TPL_01_4.html", null ],
        [ "is_compatible_array_type", "structnlohmann_1_1detail_1_1is__compatible__array__type.html", null ],
        [ "is_compatible_array_type_impl", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl.html", null ],
        [ "is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, enable_if_t< is_detected< value_type_t, CompatibleArrayType >::value and is_detected< iterator_t, CompatibleArrayType >::value and not is_iterator_traits< iterator_traits< CompatibleArrayType > >::value > >", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl_3_01BasicJsonType_00_01CompatibleA2ae7cc020294dfcc2b3bca5a9db30ddf.html", null ],
        [ "is_compatible_integer_type", "structnlohmann_1_1detail_1_1is__compatible__integer__type.html", null ],
        [ "is_compatible_integer_type_impl", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl.html", null ],
        [ "is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, enable_if_t< std::is_integral< RealIntegerType >::value and std::is_integral< CompatibleNumberIntegerType >::value and not std::is_same< bool, CompatibleNumberIntegerType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01RealIntegerType_00_01Compati3a04243716e8bda67d1ff2aead18da88.html", null ],
        [ "is_compatible_object_type", "structnlohmann_1_1detail_1_1is__compatible__object__type.html", null ],
        [ "is_compatible_object_type_impl", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl.html", null ],
        [ "is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, enable_if_t< is_detected< mapped_type_t, CompatibleObjectType >::value and is_detected< key_type_t, CompatibleObjectType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl_3_01BasicJsonType_00_01Compatible0bd988932da161d60568f9b7198a50d2.html", null ],
        [ "is_compatible_string_type", "structnlohmann_1_1detail_1_1is__compatible__string__type.html", null ],
        [ "is_compatible_string_type_impl", "structnlohmann_1_1detail_1_1is__compatible__string__type__impl.html", null ],
        [ "is_compatible_string_type_impl< BasicJsonType, CompatibleStringType, enable_if_t< is_detected_exact< typename BasicJsonType::string_t::value_type, value_type_t, CompatibleStringType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__string__type__impl_3_01BasicJsonType_00_01Compatible494e9dc742c819c61e54b8282030b5b6.html", null ],
        [ "is_compatible_type", "structnlohmann_1_1detail_1_1is__compatible__type.html", null ],
        [ "is_compatible_type_impl", "structnlohmann_1_1detail_1_1is__compatible__type__impl.html", null ],
        [ "is_compatible_type_impl< BasicJsonType, CompatibleType, enable_if_t< is_complete_type< CompatibleType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__type__impl_3_01BasicJsonType_00_01CompatibleType_00_fa54cb60e66f5c6ba93b1dd3f418b703.html", null ],
        [ "is_complete_type", "structnlohmann_1_1detail_1_1is__complete__type.html", null ],
        [ "is_complete_type< T, decltype(void(sizeof(T)))>", "structnlohmann_1_1detail_1_1is__complete__type_3_01T_00_01decltype_07void_07sizeof_07T_08_08_08_4.html", null ],
        [ "is_constructible_array_type", "structnlohmann_1_1detail_1_1is__constructible__array__type.html", null ],
        [ "is_constructible_array_type_impl", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl.html", null ],
        [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< not std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value and std::is_default_constructible< ConstructibleArrayType >::value and(std::is_move_assignable< ConstructibleArrayType >::value or std::is_copy_assignable< ConstructibleArrayType >::value) andis_detected< value_type_t, ConstructibleArrayType >::value andis_detected< iterator_t, ConstructibleArrayType >::value andis_complete_type< detected_t< value_type_t, ConstructibleArrayType > >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01BasicJsonType_00_01Construcb751ba39e14100ed41966800a3fcf4db.html", null ],
        [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01BasicJsonType_00_01Construce6fa33688da703b95649da4749cdeb98.html", null ],
        [ "is_constructible_object_type", "structnlohmann_1_1detail_1_1is__constructible__object__type.html", null ],
        [ "is_constructible_object_type_impl", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl.html", null ],
        [ "is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, enable_if_t< is_detected< mapped_type_t, ConstructibleObjectType >::value and is_detected< key_type_t, ConstructibleObjectType >::value > >", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl_3_01BasicJsonType_00_01Construb7f96efbcfd2606ccb5c84a830a60036.html", null ],
        [ "is_constructible_string_type", "structnlohmann_1_1detail_1_1is__constructible__string__type.html", null ],
        [ "is_constructible_string_type_impl", "structnlohmann_1_1detail_1_1is__constructible__string__type__impl.html", null ],
        [ "is_constructible_string_type_impl< BasicJsonType, ConstructibleStringType, enable_if_t< is_detected_exact< typename BasicJsonType::string_t::value_type, value_type_t, ConstructibleStringType >::value > >", "structnlohmann_1_1detail_1_1is__constructible__string__type__impl_3_01BasicJsonType_00_01Construe4743afb22172cdb3c5f428800835387.html", null ],
        [ "is_constructible_tuple", "structnlohmann_1_1detail_1_1is__constructible__tuple.html", null ],
        [ "is_constructible_tuple< T1, std::tuple< Args... > >", "structnlohmann_1_1detail_1_1is__constructible__tuple_3_01T1_00_01std_1_1tuple_3_01Args_8_8_8_01_4_01_4.html", null ],
        [ "is_iterator_traits", "structnlohmann_1_1detail_1_1is__iterator__traits.html", null ],
        [ "is_iterator_traits< iterator_traits< T > >", "structnlohmann_1_1detail_1_1is__iterator__traits_3_01iterator__traits_3_01T_01_4_01_4.html", null ],
        [ "is_sax", "structnlohmann_1_1detail_1_1is__sax.html", null ],
        [ "is_sax_static_asserts", "structnlohmann_1_1detail_1_1is__sax__static__asserts.html", null ],
        [ "iter_impl", "classnlohmann_1_1detail_1_1iter__impl.html", "classnlohmann_1_1detail_1_1iter__impl" ],
        [ "iteration_proxy", "classnlohmann_1_1detail_1_1iteration__proxy.html", "classnlohmann_1_1detail_1_1iteration__proxy" ],
        [ "iteration_proxy_value", "classnlohmann_1_1detail_1_1iteration__proxy__value.html", "classnlohmann_1_1detail_1_1iteration__proxy__value" ],
        [ "iterator_traits", "structnlohmann_1_1detail_1_1iterator__traits.html", null ],
        [ "iterator_traits< T *, enable_if_t< std::is_object< T >::value > >", "structnlohmann_1_1detail_1_1iterator__traits_3_01T_01_5_00_01enable__if__t_3_01std_1_1is__object_3_01T_01_4_1_1value_01_4_01_4.html", null ],
        [ "iterator_traits< T, enable_if_t< !std::is_pointer< T >::value > >", "structnlohmann_1_1detail_1_1iterator__traits_3_01T_00_01enable__if__t_3_01_9std_1_1is__pointer_3_01T_01_4_1_1value_01_4_01_4.html", null ],
        [ "iterator_types", "structnlohmann_1_1detail_1_1iterator__types.html", null ],
        [ "iterator_types< It, void_t< typename It::difference_type, typename It::value_type, typename It::pointer, typename It::reference, typename It::iterator_category > >", "structnlohmann_1_1detail_1_1iterator__types_3_01It_00_01void__t_3_01typename_01It_1_1difference_d2be8685966c97e00e99d4fd2366dc0b.html", null ],
        [ "json_ref", "classnlohmann_1_1detail_1_1json__ref.html", null ],
        [ "json_reverse_iterator", "classnlohmann_1_1detail_1_1json__reverse__iterator.html", "classnlohmann_1_1detail_1_1json__reverse__iterator" ],
        [ "json_sax_acceptor", "classnlohmann_1_1detail_1_1json__sax__acceptor.html", null ],
        [ "json_sax_dom_callback_parser", "classnlohmann_1_1detail_1_1json__sax__dom__callback__parser.html", null ],
        [ "json_sax_dom_parser", "classnlohmann_1_1detail_1_1json__sax__dom__parser.html", "classnlohmann_1_1detail_1_1json__sax__dom__parser" ],
        [ "lexer", "classnlohmann_1_1detail_1_1lexer.html", "classnlohmann_1_1detail_1_1lexer" ],
        [ "make_index_sequence", "structnlohmann_1_1detail_1_1make__index__sequence.html", null ],
        [ "make_index_sequence< 0 >", "structnlohmann_1_1detail_1_1make__index__sequence_3_010_01_4.html", null ],
        [ "make_index_sequence< 1 >", "structnlohmann_1_1detail_1_1make__index__sequence_3_011_01_4.html", null ],
        [ "make_void", "structnlohmann_1_1detail_1_1make__void.html", null ],
        [ "merge_and_renumber", "structnlohmann_1_1detail_1_1merge__and__renumber.html", null ],
        [ "merge_and_renumber< index_sequence< I1... >, index_sequence< I2... > >", "structnlohmann_1_1detail_1_1merge__and__renumber_3_01index__sequence_3_01I1_8_8_8_01_4_00_01inde4885d6f1d93a04f25932afbd429c4793.html", null ],
        [ "nonesuch", "structnlohmann_1_1detail_1_1nonesuch.html", null ],
        [ "other_error", "classnlohmann_1_1detail_1_1other__error.html", null ],
        [ "out_of_range", "classnlohmann_1_1detail_1_1out__of__range.html", null ],
        [ "output_adapter", "classnlohmann_1_1detail_1_1output__adapter.html", null ],
        [ "output_adapter_protocol", "structnlohmann_1_1detail_1_1output__adapter__protocol.html", null ],
        [ "output_stream_adapter", "classnlohmann_1_1detail_1_1output__stream__adapter.html", null ],
        [ "output_string_adapter", "classnlohmann_1_1detail_1_1output__string__adapter.html", null ],
        [ "output_vector_adapter", "classnlohmann_1_1detail_1_1output__vector__adapter.html", null ],
        [ "parse_error", "classnlohmann_1_1detail_1_1parse__error.html", "classnlohmann_1_1detail_1_1parse__error" ],
        [ "parser", "classnlohmann_1_1detail_1_1parser.html", "classnlohmann_1_1detail_1_1parser" ],
        [ "position_t", "structnlohmann_1_1detail_1_1position__t.html", "structnlohmann_1_1detail_1_1position__t" ],
        [ "primitive_iterator_t", "classnlohmann_1_1detail_1_1primitive__iterator__t.html", "classnlohmann_1_1detail_1_1primitive__iterator__t" ],
        [ "priority_tag", "structnlohmann_1_1detail_1_1priority__tag.html", null ],
        [ "priority_tag< 0 >", "structnlohmann_1_1detail_1_1priority__tag_3_010_01_4.html", null ],
        [ "serializer", "classnlohmann_1_1detail_1_1serializer.html", "classnlohmann_1_1detail_1_1serializer" ],
        [ "static_const", "structnlohmann_1_1detail_1_1static__const.html", null ],
        [ "to_json_fn", "structnlohmann_1_1detail_1_1to__json__fn.html", null ],
        [ "type_error", "classnlohmann_1_1detail_1_1type__error.html", null ],
        [ "wide_string_input_adapter", "classnlohmann_1_1detail_1_1wide__string__input__adapter.html", "classnlohmann_1_1detail_1_1wide__string__input__adapter" ],
        [ "wide_string_input_helper", "structnlohmann_1_1detail_1_1wide__string__input__helper.html", null ],
        [ "wide_string_input_helper< WideStringType, 2 >", "structnlohmann_1_1detail_1_1wide__string__input__helper_3_01WideStringType_00_012_01_4.html", null ]
      ] ],
      [ "adl_serializer", "structnlohmann_1_1adl__serializer.html", null ],
      [ "basic_json", "classnlohmann_1_1basic__json.html", "classnlohmann_1_1basic__json" ],
      [ "json_pointer", "classnlohmann_1_1json__pointer.html", "classnlohmann_1_1json__pointer" ],
      [ "json_sax", "structnlohmann_1_1json__sax.html", "structnlohmann_1_1json__sax" ]
    ] ],
    [ "std", null, [
      [ "hash< nlohmann::json >", "structstd_1_1hash_3_01nlohmann_1_1json_01_4.html", "structstd_1_1hash_3_01nlohmann_1_1json_01_4" ],
      [ "less<::nlohmann::detail::value_t >", "structstd_1_1less_3_1_1nlohmann_1_1detail_1_1value__t_01_4.html", "structstd_1_1less_3_1_1nlohmann_1_1detail_1_1value__t_01_4" ],
      [ "tuple_element< N, ::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__element_3_01N_00_01_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01IteratorType_01_4_01_4.html", null ],
      [ "tuple_size<::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__size_3_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01IteratorType_01_4_01_4.html", null ]
    ] ],
    [ "Util", "namespaceUtil.html", [
      [ "Animation", "classUtil_1_1Animation.html", "classUtil_1_1Animation" ],
      [ "BGM", "classUtil_1_1BGM.html", "classUtil_1_1BGM" ],
      [ "Color", "classUtil_1_1Color.html", "classUtil_1_1Color" ],
      [ "GameObject", "classUtil_1_1GameObject.html", "classUtil_1_1GameObject" ],
      [ "Image", "classUtil_1_1Image.html", "classUtil_1_1Image" ],
      [ "Input", "classUtil_1_1Input.html", null ],
      [ "Root", "classUtil_1_1Root.html", "classUtil_1_1Root" ],
      [ "SFX", "classUtil_1_1SFX.html", "classUtil_1_1SFX" ],
      [ "Text", "classUtil_1_1Text.html", "classUtil_1_1Text" ],
      [ "Time", "classUtil_1_1Time.html", null ],
      [ "Transform", "structUtil_1_1Transform.html", "structUtil_1_1Transform" ]
    ] ],
    [ "App", "classApp.html", null ]
];